language: node_js
node_js:
  - "6"
  - "5"
  - "4"
before_script:
  - npm install -g gulp typings
  - npm install
  - 
script: gulp build
notifications:
  slack:
    rooms:
        - nashvegastech:8YmJJoumbMc0qwu4ESM5qFjX#builds
    on_success: change
    on_failure: always
